import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Nav from "./comp/Nav/page";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={inter.className} lang="en" style={{backgroundColor:'rgba(0, 0, 0, 0.9'}}>

       {children}
      <body >

  </body>
    </html>

  );
}
